command_timeout = 2000
add_newline = false

format = "$directory$git_branch$git_status$bun$dotnet $character"

[git_branch]
symbol = "git:"
format = " [$symbol$branch]($style)"

[git_status]
format = " [$all_status$ahead_behind]($style)"
ahead = ">"
behind = "<"
diverged = "<>"
up_to_date = "="
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"

[bun]
symbol = ""
format = " [bun]($style)"

[dotnet]
symbol = ""
format = " [.NET]($style)"

[character]
success_symbol = "[>](bold green) "
error_symbol = "[!](bold red) "
vimcmd_symbol = "[<](bold yellow) "
